### ISSUE TITLE
Overlap between rbac.yaml and operators.yaml

### ISSUE THREAD

**Issue by frew** [planetscale/planetscale-releases#4]
It looks like rbac.yaml is largely overlapping with the first ~223 lines of operators.yaml.

This yields errors on step 2b of the instructions since the definitions have already been created and it also looks like there's some drift between the two files.

```
$ diff rbac.yaml operators.yaml

0a1   plural: psclusters
> ---
166c167
<   verbs: ["list", "watch"]
---
>   verbs: ["list"]
190a192,208
> - apiGroups:
>   - apiextensions.k8s.io
>   resources:
>   - customresourcedefinitions
>   verbs:
>   - '*'
> - apiGroups:
>   - monitoring.coreos.com
>   resources:
>   - alertmanagers
>   - prometheuses
>   - prometheuses/finalizers
>   - alertmanagers/finalizers
>   - servicemonitors
>   - prometheusrules
>   verbs:
>   - '*'
194d211
<   - nodes/metrics
197a215
>   - namespaces
203c221
< - nonResourceURLs: ["/metrics", "/federate"]
---
> - nonResourceURLs: ["/metrics","/federate"]
206d223
< 
```

**Comment by jvaidya** [comment]
@frew thank you for submitting the issue. @chrisrgithub @gedgar - can we get this fixed today?

**Comment by chrisrgithub** [comment]
I've tested and checked in updates to operators.yaml and rbac.yaml

**Comment by chrisrgithub** [comment]
There was some "drift" for the ClusterRole for prometheus, in rbac.yaml.   I've chosen the simpler version.  Will discuss further internally.
